# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180804_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='person',
        ),
        migrations.DeleteModel(
            name='children',
        ),
        migrations.DeleteModel(
            name='Father',
        ),
    ]
